import { defineConfig } from 'orval';
import dotenv from 'dotenv';

// Load environment variables
const ENV = process.env.NODE_ENV || 'development'
const envPath = [
    `.env.${ENV}`,
    `.env.${ENV}.local`,
]
dotenv.config({
    path: envPath,
    override: true,
});

export default defineConfig({
    flowclassApi: {
        output: {
            mode: 'tags-split', // Splits the output files by API tags
            target: './src/api/byorval/generated/api',
            client: 'react-query',
            // prettier: true,
            override: {
                header: (info) => [
                    `Generated by orval 🍺`,
                    `Do not edit manually.`,
                    ...(info.title ? [info.title] : []),
                    ...(info.description ? [info.description] : []),
                    ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
                ],
                query: {
                    useQuery: true,
                    useInfinite: true,
                },
                mutator: {
                    path: './src/api/byorval/use-custom-instance.ts',
                    name: 'useCustomInstance',
                },
            },
            schemas: './src/api/byorval/generated/model',
            // Generate types for your API responses
            tsconfig: './tsconfig.json',
        },
        input: {
            target: process.env.NEXT_PUBLIC_OPENAPI_URL || 'http://localhost:5001/api-json',
            validation: false, // Validates the OpenAPI specification
            override: {
                // Only receive js file
                transformer: './src/api/byorval/input-transformer.js',
            },
        },
        // hooks: {
        //     afterAllFilesWrite: {
        //         command: 'prettier --write',
        //         injectGeneratedDirsAndFiles: false,
        //     },
        // },
    },
});