export enum AutomationFlowErrorMessage {
  AUTOMATION_FLOW_NOT_FOUND = 'AUTOMATION_FLOW_NOT_FOUND',
  AUTOMATION_FUNCTION_NOT_FOUND = 'AUTOMATION_FUNCTION_NOT_FOUND',
  STEP_NOT_FOUND = 'STEP_NOT_FOUND',
}
