export const EnrolErrorMessage = {
  LESSON_DATE_TIME_BLOCKED: 'LESSON_DATE_TIME_BLOCKED',
  CLASS_QUOTA_IS_FULL: 'CLASS_QUOTA_IS_FULL',
  START_TIME_EARLIER_THAN_END_TIME: 'START_TIME_EARLIER_THAN_END_TIME',
  COURSE_RECRUITMENT_NOT_STARTED: 'COURSE_RECRUITMENT_NOT_STARTED',
  DATE_PICKED_IS_IN_THE_PAST: 'Date picked is in the past',
  STRIPE_CONNECT_NOT_FOUND: 'STRIPE_CONNECT_NOT_FOUND',
  DUPLICATE_ENROLLMENT: 'DUPLICATE_ENROLLMENT',
}

export const SiteErrorMessage = {
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
}

/**
 * Error messages related to institution validation and lookup
 */
export const InstitutionErrorMessage = {
  INSTITUTION_NOT_FOUND: 'INSTITUTION_NOT_FOUND',
  INVALID_DOMAIN: 'INVALID_DOMAIN',
}

/**
 * Error messages related to data not found
 */
export const DataErrorMessage = {
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
}

export const ServerErrorMessage = {
  FAILED_TO_FETCH: 'Failed to fetch',
  LOAD_FAILED: 'Load failed',
  NETWORK_ERROR: 'NETWORK_ERROR',
}

export const CouponErrorMessage = {
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_NOT_APPLY_FOR_THIS_COURSE: 'COUPON_NOT_APPLY_FOR_THIS_COURSE',
  COUPON_NOT_APPLY_FOR_USER: 'COUPON_NOT_APPLY_FOR_USER',
  COUPON_HAS_EXPIRED: 'COUPON_HAS_EXPIRED',
  COUPON_IS_NOT_ACTIVE: 'COUPON_IS_NOT_ACTIVE',
  COUPON_USED_UP: 'COUPON_USED_UP',
}
