import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTrialLessonModels1734616166796 implements MigrationInterface {
    name = 'AddTrialLessonModels1734616166796'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "trial_lesson" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "site_id" integer NOT NULL, "institution_id" integer NOT NULL, "course_ids" integer array NOT NULL DEFAULT '{}', "use_original_price" boolean NOT NULL DEFAULT false, "price" bigint NOT NULL DEFAULT '0', "enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a61339d1a0ab426a9b81109eb76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_trial_lessons_site_id" ON "trial_lesson" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "IX_trial_lessons_institution_id" ON "trial_lesson" ("institution_id") `);
        await queryRunner.query(`CREATE TABLE "class_trial_lesson" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "price" bigint NOT NULL DEFAULT '0', "trial_lesson_id" integer NOT NULL, "class_id" integer NOT NULL, CONSTRAINT "PK_f6069ca1ef0061019201364663c" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "class_trial_lesson"`);
        await queryRunner.query(`DROP INDEX "public"."IX_trial_lessons_institution_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_trial_lessons_site_id"`);
        await queryRunner.query(`DROP TABLE "trial_lesson"`);
    }

}
