import { MigrationInterface, QueryRunner } from "typeorm";

export class AddInitialUserAliasesTable1734307357322 implements MigrationInterface {
    name = 'AddInitialUserAliasesTable1734307357322'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_aliases" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "user_id" integer NOT NULL, "institution_id" integer, "ref_user_id" integer, "name" character varying NOT NULL, "phone" character varying, "is_primary" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d9d1cde77cac5f8e90f45ac7cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_user_aliases_user_id" ON "user_aliases" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "student_memo" ADD "user_alias_id" integer`);
        await queryRunner.query(`ALTER TABLE "student_form" ADD "user_alias_id" integer`);
        await queryRunner.query(`ALTER TABLE "enroll_courses" ADD "user_alias_id" integer`);
        await queryRunner.query(`CREATE INDEX "IX_student_memo_user_alias_id" ON "student_memo" ("user_alias_id") `);
        await queryRunner.query(`ALTER TABLE "user_aliases" ADD CONSTRAINT "FK_4f813c49329afad212db1d8def4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_aliases" ADD CONSTRAINT "FK_fd11624e07f3353fcafeb87a357" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_aliases" ADD CONSTRAINT "FK_fc8dab3bfdd1ce189b5199fca1c" FOREIGN KEY ("ref_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_aliases" DROP CONSTRAINT "FK_fc8dab3bfdd1ce189b5199fca1c"`);
        await queryRunner.query(`ALTER TABLE "user_aliases" DROP CONSTRAINT "FK_fd11624e07f3353fcafeb87a357"`);
        await queryRunner.query(`ALTER TABLE "user_aliases" DROP CONSTRAINT "FK_4f813c49329afad212db1d8def4"`);
        await queryRunner.query(`DROP INDEX "public"."IX_student_memo_user_alias_id"`);
        await queryRunner.query(`ALTER TABLE "enroll_courses" DROP COLUMN "user_alias_id"`);
        await queryRunner.query(`ALTER TABLE "student_form" DROP COLUMN "user_alias_id"`);
        await queryRunner.query(`ALTER TABLE "student_memo" DROP COLUMN "user_alias_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_user_aliases_user_id"`);
        await queryRunner.query(`DROP TABLE "user_aliases"`);
    }

}
