import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTableLessonQuestion1740727943871 implements MigrationInterface {
    name = 'AddTableLessonQuestion1740727943871'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "lesson_question" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "student_lesson_id" integer NOT NULL DEFAULT '0', "question" text, "answer" character varying, "parent_id" integer, CONSTRAINT "PK_c96594730ed52da2cfb92168902" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_lesson_question_institution_id" ON "lesson_question" ("institution_id") `);
        await queryRunner.query(`CREATE INDEX "IX_lesson_question_student_lesson_id" ON "lesson_question" ("student_lesson_id") `);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_type_enum" RENAME TO "notification_record_notification_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_type_enum" AS ENUM('CONFIRM_PAYMENT', 'REJECT_PAYMENT', 'REMINDER', 'APPLICATION', 'FORGET_PASSWORD', 'INVITATION', 'LESSON_POSTPONE', 'ASSIGN_COURSE', 'OTHERS', 'WAITING_FOR_PAYMENT', 'ENROLLED_IN_COURSE', 'RECEIVED_COUPON', 'UPDATE_ON_COURSE_STATUS', 'APPLIED_FOR_COURSE', 'STUDENT_REGISTERED', 'STUDENT_PAID', 'STUDENT_QUESTION', 'STUDENT_ANSWER')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" TYPE "public"."notification_record_notification_type_enum" USING "notification_type"::"text"::"public"."notification_record_notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" SET DEFAULT 'OTHERS'`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_type_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."notification_record_notification_type_enum_old" AS ENUM('CONFIRM_PAYMENT', 'REJECT_PAYMENT', 'REMINDER', 'APPLICATION', 'FORGET_PASSWORD', 'INVITATION', 'LESSON_POSTPONE', 'ASSIGN_COURSE', 'OTHERS', 'WAITING_FOR_PAYMENT', 'ENROLLED_IN_COURSE', 'RECEIVED_COUPON', 'UPDATE_ON_COURSE_STATUS', 'APPLIED_FOR_COURSE', 'STUDENT_REGISTERED', 'STUDENT_PAID')`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" TYPE "public"."notification_record_notification_type_enum_old" USING "notification_type"::"text"::"public"."notification_record_notification_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "notification_record" ALTER COLUMN "notification_type" SET DEFAULT 'OTHERS'`);
        await queryRunner.query(`DROP TYPE "public"."notification_record_notification_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_record_notification_type_enum_old" RENAME TO "notification_record_notification_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IX_lesson_question_student_lesson_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_lesson_question_institution_id"`);
        await queryRunner.query(`DROP TABLE "lesson_question"`);
    }

}
