import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableLocations1741914421447 implements MigrationInterface {
  name = 'CreateTableLocations1741914421447'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "location_room" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institutionId" integer NOT NULL, "siteId" integer NOT NULL, "name" character varying(255) NOT NULL, "capacity" integer NOT NULL, "description" text, "locationGroups" json default '[]', "equipment" json default '[]', "coordinate" json, "address" text, CONSTRAINT "PK_b33b01322a6a8c723c1283da131" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_location_room_institution_id" ON "location_room" ("institutionId")`
    )
    await queryRunner.query(`CREATE INDEX "IX_location_room_site_id" ON "location_room" ("siteId")`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "IX_location_room_institution_id"`)
    await queryRunner.query(`DROP INDEX "IX_location_room_site_id"`)
    await queryRunner.query(`DROP TABLE "location_room"`)
  }
}
