import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTableRequestTimeChange1741079385499 implements MigrationInterface {
    name = 'AddTableRequestTimeChange1741079385499'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "request_time_change" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "student_lesson_id" integer NOT NULL DEFAULT '0', "user_id" integer NOT NULL, "request_start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "request_end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" character varying, "status" character varying NOT NULL DEFAULT 'PENDING', CONSTRAINT "PK_2c93caca067e1855d95a520804b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IX_request_time_change_institution_id" ON "request_time_change" ("institution_id") `);
        await queryRunner.query(`CREATE INDEX "IX_request_time_change_student_lesson_id" ON "request_time_change" ("student_lesson_id") `);
        await queryRunner.query(`CREATE INDEX "IX_request_time_change_user_id" ON "request_time_change" ("user_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IX_request_time_change_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_request_time_change_student_lesson_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_request_time_change_institution_id"`);
        await queryRunner.query(`DROP TABLE "request_time_change"`);
    }

}
