import { MigrationInterface, QueryRunner } from 'typeorm'

export class BookingSystem1743153156380 implements MigrationInterface {
  name = 'BookingSystem1743153156380'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IX_appointment_course_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_appointment_institution_id"`)
    await queryRunner.query(
      `CREATE TABLE "availabilities" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "site_id" integer NOT NULL, "institution_id" integer NOT NULL, "course_id" integer NOT NULL, "available_schedules" jsonb, "calendar_connect_id" integer, "date_overrides" jsonb, CONSTRAINT "PK_9562bd8681d40361b1a124ea52c" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_availability_site_id" ON "availabilities" ("site_id") `
    )
    await queryRunner.query(
      `CREATE INDEX "IX_availability_institution_id" ON "availabilities" ("institution_id") `
    )
    await queryRunner.query(
      `CREATE INDEX "IX_availability_course_id" ON "availabilities" ("course_id") `
    )

    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "tuition"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "min_lesson"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "available_time_w"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "available_time_d"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "booking_condition_schedule"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "indefinitely_booking"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "cannot_schedule_within"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "default_price_id"`)
    // await queryRunner.query(`ALTER TABLE "classes" ADD "instructor_id" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "class_id" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "availability_id" integer`)
    await queryRunner.query(
      `ALTER TABLE "appointment" ADD "booking_condition" jsonb NOT NULL DEFAULT '{}'`
    )
    await queryRunner.query(`ALTER TABLE "appointment" ADD "buffer_before" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "buffer_after" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "daily_limit" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "minimum_notice_minutes" integer`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "calendar_connect_id" integer`)
    // await queryRunner.query(`ALTER TABLE "invite_site_members" ADD "name" character varying`)
    // await queryRunner.query(`ALTER TABLE "invite_site_members" ADD "phone" character varying`)
    // await queryRunner.query(
    //   `CREATE INDEX "IX_class_lessons_instructor_id" ON "class_lessons" ("instructor_id") `
    // )
    // await queryRunner.query(
    //   `CREATE INDEX "IX_classes_instructor_id" ON "classes" ("instructor_id") `
    // )
    // await queryRunner.query(
    //   `CREATE INDEX "IX_availability_institution_id" ON "appointment" ("institution_id") `
    // )
    // await queryRunner.query(
    //   `CREATE INDEX "IX_availability_course_id" ON "appointment" ("course_id") `
    // )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IX_availability_course_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_availability_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_classes_instructor_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_class_lessons_instructor_id"`)
    await queryRunner.query(`ALTER TABLE "invite_site_members" DROP COLUMN "phone"`)
    await queryRunner.query(`ALTER TABLE "invite_site_members" DROP COLUMN "name"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "calendar_connect_id"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "minimum_notice_minutes"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "daily_limit"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "buffer_after"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "buffer_before"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "booking_condition"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "availability_id"`)
    await queryRunner.query(`ALTER TABLE "appointment" DROP COLUMN "class_id"`)
    await queryRunner.query(`ALTER TABLE "classes" DROP COLUMN "instructor_id"`)
    await queryRunner.query(`ALTER TABLE "class_lessons" DROP COLUMN "instructor_id"`)
    await queryRunner.query(
      `ALTER TABLE "appointment" ADD "default_price_id" character varying NOT NULL`
    )
    await queryRunner.query(
      `ALTER TABLE "appointment" ADD "cannot_schedule_within" integer NOT NULL`
    )
    await queryRunner.query(
      `ALTER TABLE "appointment" ADD "indefinitely_booking" boolean NOT NULL DEFAULT false`
    )
    await queryRunner.query(`ALTER TABLE "appointment" ADD "booking_condition_schedule" jsonb`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "available_time_d" jsonb`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "available_time_w" jsonb`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "min_lesson" integer NOT NULL`)
    await queryRunner.query(`ALTER TABLE "appointment" ADD "tuition" integer NOT NULL`)
    await queryRunner.query(`DROP INDEX "public"."IX_availability_course_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_availability_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_availability_site_id"`)
    await queryRunner.query(`DROP TABLE "availabilities"`)
    await queryRunner.query(
      `CREATE INDEX "IX_appointment_institution_id" ON "appointment" ("institution_id") `
    )
    await queryRunner.query(
      `CREATE INDEX "IX_appointment_course_id" ON "appointment" ("course_id") `
    )
  }
}
