import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddMeetingIntegration1744986412011 implements MigrationInterface {
  name = 'AddMeetingIntegration1744986412011'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "integration_calendar" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "provider" character varying NOT NULL, "calendar_account_id" character varying, "api_key" character varying, "calendar_access_token" character varying, "calendar_refresh_token" character varying, "calendar_name" character varying, "is_enabled" boolean NOT NULL DEFAULT true, "status" character varying, CONSTRAINT "PK_dc4f1a90b865c947fb03c27a83f" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_integration_calendar_institution_id" ON "integration_calendar" ("institution_id") `
    )
    await queryRunner.query(
      `CREATE TABLE "integration_online_meeting" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "provider" character varying NOT NULL, "account_id" character varying, "api_key" character varying, "access_token" character varying, "refresh_token" character varying, "is_enabled" boolean NOT NULL DEFAULT true, "status" character varying, CONSTRAINT "PK_26238e3115ac95e3d20217fd384" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_online_meeting_connects_institution_id" ON "integration_online_meeting" ("institution_id") `
    )
    await queryRunner.query(
      `ALTER TABLE "class_lessons" ADD "lesson_meeting_url" character varying`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "class_lessons" DROP COLUMN "lesson_meeting_url"`)
    await queryRunner.query(`DROP INDEX "public"."IX_online_meeting_connects_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_online_meeting_connects_site_id"`)
    await queryRunner.query(`DROP TABLE "integration_online_meeting"`)
    await queryRunner.query(`DROP INDEX "public"."IX_integration_calendar_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_integration_calendar_site_id"`)
    await queryRunner.query(`DROP TABLE "integration_calendar"`)
    await queryRunner.query(
      `CREATE TABLE IF NOT EXISTS "calendar_connects" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "site_id" integer NOT NULL, "institution_id" integer NOT NULL, "provider" character varying NOT NULL, "calendar_account_id" character varying, "api_key" character varying, "calendar_access_token" character varying, "calendar_refresh_token" character varying, "calendar_name" character varying, "is_enabled" boolean NOT NULL DEFAULT true, "status" character varying, CONSTRAINT "PK_calendar_connects" PRIMARY KEY ("id"))`
    )
  }
}
