import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddN8NWorkflowIdOfInstitution1745804714147 implements MigrationInterface {
  name = 'AddN8NWorkflowIdOfInstitution1745804714147'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "institution_workflow" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "workflow_id" character varying NOT NULL, "institution_id" integer NOT NULL, CONSTRAINT "PK_25aa5550e29dab5654531adac17" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_institution_workflow_workflow_id" ON "institution_workflow" ("workflow_id") `
    )
    await queryRunner.query(
      `CREATE INDEX "IX_institution_workflow_institution_id" ON "institution_workflow" ("institution_id") `
    )
    await queryRunner.query(`ALTER TABLE "institutions" ADD "n8n_workflow_id" character varying`)
    await queryRunner.query(`ALTER TABLE "request_time_change" DROP COLUMN "status"`)
    await queryRunner.query(
      `CREATE TYPE "public"."request_time_change_status_enum" AS ENUM('APPROVED', 'REJECTED', 'PENDING')`
    )
    await queryRunner.query(
      `ALTER TABLE "request_time_change" ADD "status" "public"."request_time_change_status_enum" NOT NULL DEFAULT 'PENDING'`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "request_time_change" DROP COLUMN "status"`)
    await queryRunner.query(`DROP TYPE "public"."request_time_change_status_enum"`)
    await queryRunner.query(
      `ALTER TABLE "request_time_change" ADD "status" character varying NOT NULL DEFAULT 'PENDING'`
    )
    await queryRunner.query(`ALTER TABLE "institutions" DROP COLUMN "n8n_workflow_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_institution_workflow_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_institution_workflow_workflow_id"`)
    await queryRunner.query(`DROP TABLE "institution_workflow"`)
  }
}
