import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddCustomMessageTable1746151193512 implements MigrationInterface {
  name = 'AddCustomMessageTable1746151193512'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "custom_message" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "content" character varying, "name" character varying DEFAULT '', "type" character varying NOT NULL, "variables" jsonb, "email_notification" boolean NOT NULL DEFAULT true, "whatsapp_notification" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_04c6a03964fec907c773d88d81e" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_custom_message_institution_id" ON "custom_message" ("institution_id") `
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IX_custom_message_institution_id"`)
    await queryRunner.query(`DROP TABLE "custom_message"`)
  }
}
