import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddStudentNotificationSettingsTable1747968538080 implements MigrationInterface {
  name = 'AddStudentNotificationSettingsTable1747968538080'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "student_notification_setting" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "student_id" integer NOT NULL, "institution_id" integer NOT NULL, "notification_type" character varying NOT NULL, "whatsapp" boolean NOT NULL, "email" boolean NOT NULL, CONSTRAINT "PK_3cc8d950e016ca9333649bbfe1d" PRIMARY KEY ("id"))`
    )

    // Add foreign key constraints
    await queryRunner.query(
      `ALTER TABLE "student_notification_setting" ADD CONSTRAINT "FK_student_notification_setting_student_id" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE`
    )
    await queryRunner.query(
      `ALTER TABLE "student_notification_setting" ADD CONSTRAINT "FK_student_notification_setting_institution_id" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE CASCADE`
    )

    // Add performance index for common query pattern
    await queryRunner.query(
      `CREATE INDEX "IDX_student_notification_setting_lookup" ON "student_notification_setting" ("student_id", "institution_id", "notification_type")`
    )

  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop indexes and constraints before dropping table
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_student_notification_setting_lookup"`)
    await queryRunner.query(`ALTER TABLE "student_notification_setting" DROP CONSTRAINT IF EXISTS "FK_student_notification_setting_institution_id"`)
    await queryRunner.query(`ALTER TABLE "student_notification_setting" DROP CONSTRAINT IF EXISTS "FK_student_notification_setting_student_id"`)
    await queryRunner.query(`DROP TABLE "student_notification_setting"`)
  }
}
