import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddXeroIntegrationTable1749107131076 implements MigrationInterface {
  name = 'AddXeroIntegrationTable1749107131076'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "xero_contact" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "user_id" integer NOT NULL, "institution_id" integer NOT NULL, "contact_id" character varying NOT NULL, CONSTRAINT "PK_0ef51097f4b50b02c324d01ef1f" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(`CREATE INDEX "IX_xero_contact_user_id" ON "xero_contact" ("user_id") `)
    await queryRunner.query(
      `CREATE INDEX "IX_xero_contact_institution_id" ON "xero_contact" ("institution_id") `
    )
    await queryRunner.query(`ALTER TABLE "classes" ADD "xero_item_id" character varying`)

    await queryRunner.query(`ALTER TABLE "invoices" ADD "xero_invoice_id" character varying`)
    await queryRunner.query(
      `CREATE TABLE "integration_xero" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "user_id" integer NOT NULL, "institution_id" integer NOT NULL, "secret_token" text NOT NULL, "client_id" text NOT NULL, "status" character varying, "session_data" text, "session_expiration" TIMESTAMP WITH TIME ZONE, "tenant_id" text, "account_code" character varying, "default_account_id" character varying, CONSTRAINT "PK_de108bc6a63d36c4e033bb2fcb4" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_39a1f5ba3c762d4b1aa389c177" ON "integration_xero" ("user_id") `
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_60b33b4b93a12a175a097c78b5" ON "integration_xero" ("institution_id") `
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IDX_60b33b4b93a12a175a097c78b5"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_39a1f5ba3c762d4b1aa389c177"`)
    await queryRunner.query(`DROP TABLE "integration_xero"`)
    await queryRunner.query(`DROP INDEX "public"."IX_xero_contact_institution_id"`)
    await queryRunner.query(`DROP INDEX "public"."IX_xero_contact_user_id"`)
    await queryRunner.query(`DROP TABLE "xero_contact"`)
    await queryRunner.query(`ALTER TABLE "classes" DROP COLUMN "xero_item_id"`)
    await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "xero_invoice_id"`)
  }
}
