import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddInstructorProfileTable1753175979000 implements MigrationInterface {
  name = 'AddInstructorProfileTable1753175979000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create instructor_profiles table
    await queryRunner.query(
      `CREATE TABLE "instructor_profiles" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP WITH TIME ZONE,
        "created_by" integer,
        "updated_by" integer,
        "user_role_id" integer NOT NULL,
        "is_rates_enabled" boolean NOT NULL DEFAULT false,
        "is_active" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_instructor_profiles" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_instructor_profiles_user_role_id" UNIQUE ("user_role_id")
      )`
    )

    // Create index for user_role_id
    await queryRunner.query(
      `CREATE INDEX "IX_instructor_profiles_user_role_id" ON "instructor_profiles" ("user_role_id")`
    )

    // Add instructor_profile_id column to user_roles table
    await queryRunner.query(`ALTER TABLE "user_roles" ADD "instructor_profile_id" integer`)

    // Create index for instructor_profile_id in user_roles
    await queryRunner.query(
      `CREATE INDEX "IX_user_roles_instructor_profile_id" ON "user_roles" ("instructor_profile_id")`
    )

    // Populate instructor_profiles for existing instructors
    await queryRunner.query(`
      INSERT INTO "instructor_profiles" ("user_role_id", "is_rates_enabled", "is_active", "created_at", "updated_at")
      SELECT 
        ur.id as user_role_id,
        ur.is_instructor_rates_enabled as is_rates_enabled,
        true as is_active,
        now() as created_at,
        now() as updated_at
      FROM "user_roles" ur
      WHERE ur.is_instructor = true
    `)

    // Update user_roles to set instructor_profile_id
    await queryRunner.query(`
      UPDATE "user_roles" ur
      SET instructor_profile_id = ip.id
      FROM "instructor_profiles" ip
      WHERE ur.id = ip.user_role_id
    `)

    // Add instructor_profile_id column to instructor_rates table
    await queryRunner.query(`ALTER TABLE "instructor_rates" ADD "instructor_profile_id" integer`)

    // Update instructor_rates to use instructor_profile_id from the corresponding user_role
    await queryRunner.query(`
      UPDATE "instructor_rates" ir
      SET instructor_profile_id = ur.instructor_profile_id
      FROM "user_roles" ur
      WHERE ir.user_role_id = ur.id
      AND ur.instructor_profile_id IS NOT NULL
    `)

    // Create index for instructor_profile_id in instructor_rates
    await queryRunner.query(
      `CREATE INDEX "IX_instructor_rates_instructor_profile_id" ON "instructor_rates" ("instructor_profile_id")`
    )

    // Make instructor_profile_id NOT NULL in instructor_rates (after populating data)
    await queryRunner.query(
      `ALTER TABLE "instructor_rates" ALTER COLUMN "instructor_profile_id" SET NOT NULL`
    )

    // Drop the old user_role_id column from instructor_rates
    await queryRunner.query(`ALTER TABLE "instructor_rates" DROP COLUMN "user_id"`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Add back user_role_id column to instructor_rates
    await queryRunner.query(`ALTER TABLE "instructor_rates" ADD "user_role_id" integer`)

    // Restore user_role_id data from instructor_profile relationship
    await queryRunner.query(`
      UPDATE "instructor_rates" ir
      SET user_role_id = ip.user_role_id
      FROM "instructor_profiles" ip
      WHERE ir.instructor_profile_id = ip.id
    `)

    // Make user_role_id NOT NULL
    await queryRunner.query(
      `ALTER TABLE "instructor_rates" ALTER COLUMN "user_role_id" SET NOT NULL`
    )

    // Create index for user_role_id
    await queryRunner.query(
      `CREATE INDEX "IX_instructor_rates_user_role_id" ON "instructor_rates" ("user_role_id")`
    )

    // Drop instructor_profile_id column from instructor_rates
    await queryRunner.query(`DROP INDEX "IX_instructor_rates_instructor_profile_id"`)
    await queryRunner.query(`ALTER TABLE "instructor_rates" DROP COLUMN "instructor_profile_id"`)

    // Drop instructor_profile_id column from user_roles
    await queryRunner.query(`DROP INDEX "IX_user_roles_instructor_profile_id"`)
    await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "instructor_profile_id"`)

    // Drop instructor_profiles table
    await queryRunner.query(`DROP INDEX "IX_instructor_profiles_user_role_id"`)
    await queryRunner.query(`DROP TABLE "instructor_profiles"`)
  }
}
