import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateFlexibleClassSchedules1753470000000 implements MigrationInterface {
  name = 'CreateFlexibleClassSchedules1753470000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create enum type for selection mode
    await queryRunner.query(
      `CREATE TYPE "public"."class_regular_periods_selection_mode_enum" AS ENUM('MUST_SELECT_ENTIRE_PERIOD', 'MUST_SELECT_UNTIL_END', 'ALLOW_CUSTOM_SELECTION')`
    )

    // Create the main class_regular_schedules table
    await queryRunner.query(
      `CREATE TABLE "class_regular_schedules" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP WITH TIME ZONE,
        "created_by" integer,
        "updated_by" integer,
        "site_id" integer NOT NULL,
        "institution_id" integer NOT NULL,
        "course_id" integer NOT NULL,
        "class_id" integer NOT NULL,
        "period_repeat_format" jsonb DEFAULT '{"every": 1, "unit": "weeks"}'::jsonb,
        "period_repeat_count" integer NOT NULL DEFAULT 0,
        "gap_between_periods" jsonb DEFAULT '{"every": 0, "unit": "days"}'::jsonb,
        "date_overrides" jsonb NOT NULL DEFAULT '[]',
        "selection_mode" "public"."class_regular_periods_selection_mode_enum" NOT NULL DEFAULT 'MUST_SELECT_ENTIRE_PERIOD',
        CONSTRAINT "PK_class_regular_schedules" PRIMARY KEY ("id")
      )`
    )

    // Create indexes for the schedules table
    await queryRunner.query(
      `CREATE INDEX "IX_class_regular_schedules_site_id" ON "class_regular_schedules" ("site_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_class_regular_schedules_institution_id" ON "class_regular_schedules" ("institution_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_class_regular_schedules_course_id" ON "class_regular_schedules" ("course_id")`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_class_regular_schedules_class_id" ON "class_regular_schedules" ("class_id")`
    )

    // create a new column 'regular_schedule_id' in the classes table
    await queryRunner.query(
      `ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "regular_schedule_id" integer`
    )

    // Check if class_regular_periods table exists, if not create it
    const tableExists = await queryRunner.hasTable('class_regular_periods')

    if (!tableExists) {
      // Create the class_regular_periods table if it doesn't exist
      await queryRunner.query(
        `CREATE TABLE "class_regular_periods" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
          "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
          "deleted_at" TIMESTAMP WITH TIME ZONE,
          "created_by" integer,
          "updated_by" integer,
          "class_id" integer NOT NULL,
          "lesson_repeat_format_id" integer,
          "start_time" TIMESTAMP WITH TIME ZONE,
          "end_time" TIMESTAMP WITH TIME ZONE,
          "regular_schedule_id" integer NOT NULL,
          CONSTRAINT "PK_class_regular_periods" PRIMARY KEY ("id")
        )`
      )
    } else {
      // Add new columns to existing table
      await queryRunner.query(
        `ALTER TABLE "class_regular_periods" ADD COLUMN IF NOT EXISTS "start_time" TIMESTAMP WITH TIME ZONE`
      )
      await queryRunner.query(
        `ALTER TABLE "class_regular_periods" ADD COLUMN IF NOT EXISTS "end_time" TIMESTAMP WITH TIME ZONE`
      )
      await queryRunner.query(
        `ALTER TABLE "class_regular_periods" ADD COLUMN IF NOT EXISTS "regular_schedule_id" integer NOT NULL DEFAULT 0`
      )

      // Remove the default after adding the column
      await queryRunner.query(
        `ALTER TABLE "class_regular_periods" ALTER COLUMN "regular_schedule_id" DROP DEFAULT`
      )
    }

    await queryRunner.query(
      `ALTER TABLE "class_lessons" ADD COLUMN IF NOT EXISTS "regular_schedule_id" integer`
    )

    // Create indexes for the periods table
    await queryRunner.query(
      `CREATE INDEX "IX_class_regular_period_schedules_v2_period_id" ON "class_regular_periods" ("regular_schedule_id")`
    )

    // Add foreign key constraint from periods to schedules
    await queryRunner.query(
      `ALTER TABLE "class_regular_periods" ADD CONSTRAINT "FK_class_regular_periods_regular_schedule" FOREIGN KEY ("regular_schedule_id") REFERENCES "class_regular_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`
    )

    // Add foreign key constraint for repeat format (if repeat_formats table exists)
    const repeatFormatsExists = await queryRunner.hasTable('repeat_formats')
    if (repeatFormatsExists) {
      await queryRunner.query(
        `ALTER TABLE "class_regular_periods" ADD CONSTRAINT "FK_class_regular_periods_lesson_repeat_format" FOREIGN KEY ("lesson_repeat_format_id") REFERENCES "repeat_formats"("id") ON DELETE SET NULL ON UPDATE NO ACTION`
      )
    }

    // Add foreign key constraint for classes (if classes table exists)
    const classesExists = await queryRunner.hasTable('classes')
    if (classesExists) {
      await queryRunner.query(
        `ALTER TABLE "class_regular_schedules" ADD CONSTRAINT "FK_class_regular_schedules_class" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`
      )
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop all tables and constraints in reverse order
    await queryRunner.query(
      `ALTER TABLE "class_lessons" DROP COLUMN IF EXISTS "regular_schedule_id"`
    )

    // Drop the periods table first (it depends on schedules)
    await queryRunner.query(`DROP TABLE IF EXISTS "class_regular_periods"`)

    // Drop the schedules table
    await queryRunner.query(`DROP TABLE IF EXISTS "class_regular_schedules"`)

    // Drop the enum type
    await queryRunner.query(
      `DROP TYPE IF EXISTS "public"."class_regular_periods_selection_mode_enum"`
    )
  }
}
