import { MigrationInterface, QueryRunner } from "typeorm";

export class AddActivePaidSubscriptionPlanRecordTable1753874325544 implements MigrationInterface {
    name = 'AddActivePaidSubscriptionPlanRecordTable1753874325544'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
      CREATE TABLE "activepaid_subscription_plan_records" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP WITH TIME ZONE,
        "created_by" integer,
        "updated_by" integer,
        "plan_id" integer NOT NULL,
        "site_id" integer NOT NULL,
        "purchase_date" TIMESTAMP WITH TIME ZONE NOT NULL,
        "expiry_date" TIMESTAMP WITH TIME ZONE NOT NULL,
        "base_user_quantity" integer NOT NULL DEFAULT '1',
        "notification_quantity" integer NOT NULL DEFAULT '0',
        "school_quantity" integer NOT NULL DEFAULT '1',
        "setup_fee_quantity" integer NOT NULL DEFAULT '1',
        "admin_quantity" integer NOT NULL DEFAULT '1',
        "tutor_quantity" integer NOT NULL DEFAULT '1',
        "class_type_enable" jsonb,
        "feature_enable" jsonb,
        "notification_channels" jsonb,
        "promotion_tier" jsonb,
        "integration" jsonb,
        "customer_support_tier" character varying,
        "total_price" integer,
        "currency" character varying(3),
        "stripe_subscription_id" character varying,
        "is_trial" boolean NOT NULL DEFAULT false,
        "app" character varying NOT NULL DEFAULT 'activepaid',
        "original_plan_type" character varying,
        "upgrade_scheduled_for" TIMESTAMP WITH TIME ZONE,
        "downgrade_scheduled_for" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_d57bf1aef8b6ecc71428d5762cd" PRIMARY KEY ("id"),
        CONSTRAINT "FK_activepaid_plan_id" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id")
      )
    `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "activepaid_subscription_plan_records"`);
    }
}
