import { MigrationInterface, QueryRunner } from 'typeorm'

export class Runs1755228433708 implements MigrationInterface {
  name = 'Runs1755228433708'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "sites_feature_enabled" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "feature" character varying(255) NOT NULL, "site_ids" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_0c2c474431089f56b426b620e9c" PRIMARY KEY ("id"))`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "sites_feature_enabled"`)
  }
}
