import { MigrationInterface, QueryRunner } from 'typeorm'

export class PresetSubscriptionPlans1756912764142 implements MigrationInterface {
  name = 'PresetSubscriptionPlans1756912764142'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "subscription_preset_plan" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "name" character varying NOT NULL, "base_user_quantity" integer NOT NULL DEFAULT '1', "notification_quantity" integer NOT NULL DEFAULT '0', "school_quantity" integer NOT NULL DEFAULT '1', "setup_fee_quantity" integer NOT NULL DEFAULT '1', "admin_quantity" integer NOT NULL DEFAULT '1', "tutor_quantity" integer NOT NULL DEFAULT '1', "class_type_enable" jsonb, "feature_enable" jsonb, "notification_channels" jsonb, "promotion_tier" jsonb, "integration" jsonb, "customer_support_tier" character varying, "total_price" integer, "currency" character varying(3), "stripe_product_id" character varying, "prices" jsonb, "is_trial" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3d132757d3df8b1fff25903f6a5" PRIMARY KEY ("id"))`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "subscription_preset_plan"`)
  }
}
