import { MigrationInterface, QueryRunner } from 'typeorm'

export class RunAddMaterialClassTable1758591898410 implements MigrationInterface {
  name = 'RunAddMaterialClassTable1758591898410'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "media_materials" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "type" character varying NOT NULL, "file_type" character varying, "class_material_id" integer, "drive_id" character varying, "file_id" character varying, "name" character varying NOT NULL, "expiry_date" TIMESTAMP WITH TIME ZONE, "description" text, "link" text, "size" integer default 0, "student_submission_id" integer, "teacher_feedback_id" integer, CONSTRAINT "PK_43c691714e4ea1b2c8ff906b851" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE TABLE "class_materials" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "name" character varying NOT NULL, "class_lesson_id" integer NOT NULL, "class_id" integer NOT NULL, "course_id" integer NOT NULL, "institution_id" integer NOT NULL, CONSTRAINT "PK_d6edfd6a08a4402a7ae8a931df0" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_300fc30acf97053d15543e15dc" ON "class_materials" ("class_lesson_id", "class_id", "course_id", "institution_id") `
    )
    await queryRunner.query(
      `CREATE TABLE "student_submissions" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "student_id" integer NOT NULL, "student_lesson_id" integer NOT NULL, "class_lesson_id" integer NOT NULL, CONSTRAINT "PK_9eeab3d07d38ce235f6d1afd105" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_5da169739884ed6119a5897538" ON "student_submissions" ("student_id", "student_lesson_id", "class_lesson_id") `
    )
    await queryRunner.query(
      `CREATE TABLE "teacher_feedback" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "teacher_id" integer NOT NULL, "student_lesson_id" integer NOT NULL, "class_lesson_id" integer NOT NULL,CONSTRAINT "PK_60852f48b21e5badd2253d529c3" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_08310c8e6bcb892b0878b27725" ON "teacher_feedback" ("teacher_id", "student_lesson_id", "class_lesson_id") `
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IDX_08310c8e6bcb892b0878b27725"`)
    await queryRunner.query(`DROP TABLE "teacher_feedback"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_5da169739884ed6119a5897538"`)
    await queryRunner.query(`DROP TABLE "student_submissions"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_300fc30acf97053d15543e15dc"`)
    await queryRunner.query(`DROP TABLE "class_materials"`)
    await queryRunner.query(`DROP TABLE "media_materials"`)
  }
}
