import { MigrationInterface, QueryRunner } from 'typeorm'

export class RescheduleSettings1759369497189 implements MigrationInterface {
  name = 'RescheduleSettings1759369497189'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "reschedule_settings" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" integer, "updated_by" integer, "institution_id" integer NOT NULL, "select_course" boolean NOT NULL DEFAULT true, "select_class" boolean NOT NULL DEFAULT true, "minimum_hours_before_request" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0a21dadc454b52c23da642012a7" PRIMARY KEY ("id"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IX_reschedule_settings_institution_id" ON "reschedule_settings" ("institution_id") `
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IX_reschedule_settings_institution_id"`)
    await queryRunner.query(`DROP TABLE "reschedule_settings"`)
  }
}
